### ISSUE TITLE
不太清楚具体是啥情况，第一次运行提示：No module named 'tools'，之后每次运行又都变成目录错误

### ISSUE THREAD

**Issue by BoosterCore** [AIFSH/ComfyUI-GPT_SoVITS#14]
我用的是portable最新版本，第一遍运行，得到如下错误信息：

`!!!GPT_SoVITS path was added to K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages/users.pth
 if meet `No module` error,try `python main.py` again
GPT_SoVITS use cache models,make sure your 'pretrained_models' complete
Traceback (most recent call last):
  File "K:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\__init__.py", line 36, in <module>
    from .nodes import LoadSRT,LoadAudio, GPT_SOVITS_INFER, PreViewAudio,GPT_SOVITS_FT, GPT_SOVITS_TTS
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\nodes.py", line 8, in <module>
    from tools.i18n.i18n import I18nAuto
ModuleNotFoundError: No module named 'tools'

Cannot import K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS module for custom nodes: No module named 'tools'`

之后再次运行时，上面的错误没了，每次都变成如下错误：

`!!!GPT_SoVITS path was added to K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages/users.pth
 if meet `No module` error,try `python main.py` again
GPT_SoVITS use cache models,make sure your 'pretrained_models' complete
Traceback (most recent call last):
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\pretrained_models/chinese-roberta-wwm-ext-large'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\__init__.py", line 36, in <module>
    from .nodes import LoadSRT,LoadAudio, GPT_SOVITS_INFER, PreViewAudio,GPT_SOVITS_FT, GPT_SOVITS_TTS
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\nodes.py", line 10, in <module>
    from .inference import dict_language,get_tts_wav
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\inference.py", line 23, in <module>
    tokenizer = AutoTokenizer.from_pretrained(bert_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 804, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 637, in get_tokenizer_config
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

Cannot import K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS module for custom nodes: Incorrect path_or_model_id: 'K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\pretrained_models/chinese-roberta-wwm-ext-large'. Please provide either the path to a local folder or the repo_id of a model on the Hub.`

**Comment by AIFSH** [comment]
报错信息很清楚，自己解决

**Comment by BoosterCore** [comment]
感谢，最后查了一下，还是卡在模型下载这块，阅读了readme.md，下载了权重文件后解决了！
