### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 385766470** [AIFSH/ComfyUI-GPT_SoVITS#15]
G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2>runtime\python.exe webui.py
Traceback (most recent call last):
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\simplejson\__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\simplejson\decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\simplejson\decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\webui.py", line 48, in <module>
    import gradio as gr
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\components.py", line 35, in <module>
    from gradio.blocks import Block
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\blocks.py", line 33, in <module>
    from gradio import (
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\gradio\strings.py", line 37, in <module>
    updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
  File "G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2\runtime\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

G:\GPT-SoVITS\beta\GPT-SoVITS-beta0306fix2\GPT-SoVITS-beta0306fix2>pause
请按任意键继续. . .

**Comment by AIFSH** [comment]
发错 issue 了吧
