### ISSUE TITLE
ImportError: cannot import name 'python_exec' from 'config ？

### ISSUE THREAD

**Issue by samen168** [AIFSH/ComfyUI-GPT_SoVITS#20]
[2024-05-30 15:56] Traceback (most recent call last):
  File "H:\sd\sd-webui-aki-v4.5-comfy\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\sd\sd-webui-aki-v4.5-comfy\custom_nodes\ComfyUI-GPT_SoVITS\__init__.py", line 37, in <module>
    from .nodes import LoadSRT,LoadAudio, GPT_SOVITS_INFER, PreViewAudio,GPT_SOVITS_FT, GPT_SOVITS_TTS
  File "H:\sd\sd-webui-aki-v4.5-comfy\custom_nodes\ComfyUI-GPT_SoVITS\nodes.py", line 13, in <module>
    from .finetune import open1abc,default_batch_size,open1Ba,open1Bb
  File "H:\sd\sd-webui-aki-v4.5-comfy\custom_nodes\ComfyUI-GPT_SoVITS\finetune.py", line 7, in <module>
    from config import python_exec
ImportError: cannot import name 'python_exec' from 'config' (H:\sd\sd-webui-aki-v4.5-comfy\custom_nodes\ComfyUI-BiRefNet-ZHO\config.py)

**Comment by samen168** [comment]
嘛半成品，第二次尝试了，浪费时间，用作者整合包去！

**Comment by drake7707** [comment]
Unfortunately both this and ComfyUI-BiRefNet-ZHO nodes have a config.py module. This error is because it loads the wrong config.py
