### ISSUE TITLE
Error of Jieba_fast

### ISSUE THREAD

**Issue by zhenyuanzhou** [AIFSH/ComfyUI-GPT_SoVITS#5]
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\__init__.py", line 27, in <module>
    from .nodes import LoadSRT,LoadAudio, GPT_SOVITS_INFER, PreViewAudio,GPT_SOVITS_FT, GPT_SOVITS_TTS
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\nodes.py", line 10, in <module>
    from .inference import dict_language,get_tts_wav
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\inference.py", line 34, in <module>
    from GPT_SoVITS.text.cleaner import clean_text
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\GPT_SoVITS\text\cleaner.py", line 1, in <module>
    from text import chinese, japanese, cleaned_text_to_sequence, symbols, english
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\GPT_SoVITS\text\chinese.py", line 9, in <module>
    from text.tone_sandhi import ToneSandhi
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GPT_SoVITS\GPT_SoVITS\text\tone_sandhi.py", line 17, in <module>
    import jieba_fast as jieba
ModuleNotFoundError: No module named 'jieba_fast'

I installed jieba_fast, but still error.

**Comment by AIFSH** [comment]
try to jieba_fast repo find answer

**Comment by zhenyuanzhou** [comment]
I found the problem, I switched python 3.11 to 3.10 or 3.9 can solve the problem
